# generated by datamodel-codegen:
#   filename:  v1-ade.json

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import BaseModel, Field, RootModel


class AsyncExtractRequest(BaseModel):
    """
    Request model for async extract endpoint.

    Extends ExtractRequest with output_save_url for ZDR support.
    """

    markdown: Optional[Union[bytes, str]] = Field(
        None,
        description='The Markdown file or Markdown content to extract data from.',
        title='Markdown',
    )
    markdown_url: Optional[str] = Field(
        None,
        description='The URL to the Markdown file to extract data from.',
        title='Markdown Url',
    )
    model: Optional[str] = Field(
        None,
        description='The version of the model to use for extraction. Use `extract-latest` to use the latest version.',
        title='Model',
    )
    output_save_url: Optional[str] = Field(
        None,
        description='If zero data retention (ZDR) is enabled, you must enter a URL for the extracted output to be saved to. When ZDR is enabled, the extracted content will not be in the API response.',
        title='Output Save Url',
    )
    schema_: str = Field(
        ...,
        alias='schema',
        description='JSON schema for field extraction. This schema determines what key-values pairs are extracted from the Markdown. The schema must be a valid JSON object and will be validated before processing the document.',
        title='Schema',
    )
    strict: Optional[bool] = Field(
        False,
        description='If True, reject schemas with unsupported fields (HTTP 422). If False, prune unsupported fields and continue. Only applies to extract versions that support schema validation.',
        title='Strict',
    )


class BuildSchemaRequest(BaseModel):
    markdown_urls: Optional[list[str]] = Field(
        None,
        description='URLs to Markdown files to analyze for schema generation.',
        title='Markdown Urls',
    )
    markdowns: Optional[list[Union[bytes, str]]] = Field(
        None,
        description='Markdown files or inline content strings to analyze for schema generation. Multiple documents can be provided for better schema coverage.',
        title='Markdowns',
    )
    model: Optional[str] = Field(
        None,
        description='The version of the model to use for schema generation. Use `extract-latest` to use the latest version.',
        title='Model',
    )
    prompt: Optional[str] = Field(
        None,
        description='Instructions for how to generate or modify the schema.',
        title='Prompt',
    )
    schema_: Optional[str] = Field(
        None,
        alias='schema',
        description='Existing JSON schema to iterate on or refine.',
        title='Schema',
    )


class ClassificationItem(BaseModel):
    """
    A single page-level classification result.
    """

    class_: str = Field(
        ...,
        alias='class',
        description="Predicted class label or 'unknown'.",
        title='Class',
    )
    page: int = Field(..., description='Page number (0-based).', title='Page')
    reason: Optional[str] = Field(
        '', description='Reason for the classification (for debugging).', title='Reason'
    )
    suggested_class: Optional[str] = Field(
        None,
        description="Proposed class when the prediction is 'unknown'.",
        title='Suggested Class',
    )


class ClassifyClass(BaseModel):
    """
    A single classification option: a class name plus optional description.
    """

    class_: str = Field(
        ..., alias='class', description='Name of the class.', title='Class'
    )
    description: Optional[str] = Field(
        None,
        description='Detailed description of what this class represents.',
        title='Description',
    )


class ClassifyMetadata(BaseModel):
    """
    Metadata for the classify response.
    """

    credit_usage: float = Field(..., title='Credit Usage')
    duration_ms: int = Field(..., title='Duration Ms')
    filename: str = Field(..., title='Filename')
    job_id: Optional[str] = Field('', title='Job Id')
    org_id: Optional[str] = Field(None, title='Org Id')
    page_count: int = Field(..., title='Page Count')
    version: Optional[str] = Field(None, title='Version')


class ClassifyRequest(BaseModel):
    classes: list[ClassifyClass] = Field(
        ...,
        description="The possible classes that can be assigned to pages in the document. Each entry is an object with a `class` name and an optional `description`. Only one class is assigned per page; unclassifiable pages receive 'unknown'. Can be provided as a JSON string in form data.",
        title='Classes',
    )
    document: Optional[bytes] = Field(
        None,
        description='A file to be classified. Either this parameter or the `document_url` parameter must be provided.',
        title='Document',
    )
    document_url: Optional[str] = Field(
        None,
        description='The URL of the document to be classified. Either this parameter or the `document` parameter must be provided.',
        title='Document Url',
    )
    model: Optional[str] = Field(
        None,
        description='Classification model version. Defaults to the latest.',
        title='Model',
    )


class ClassifyResponse(BaseModel):
    """
    Response model for the classify endpoint.
    """

    classification: list[ClassificationItem] = Field(..., title='Classification')
    metadata: ClassifyMetadata


class CustomPromptKey(Enum):
    """
    Chunk types that support custom prompts.
    """

    figure = 'figure'


class CustomPrompts(RootModel[dict[str, str]]):
    """
    Map of chunk type to custom prompt string.
    """

    root: dict[str, str]


class ExtractRequest(BaseModel):
    markdown: Optional[Union[bytes, str]] = Field(
        None,
        description='The Markdown file or Markdown content to extract data from.',
        title='Markdown',
    )
    markdown_url: Optional[str] = Field(
        None,
        description='The URL to the Markdown file to extract data from.',
        title='Markdown Url',
    )
    model: Optional[str] = Field(
        None,
        description='The version of the model to use for extraction. Use `extract-latest` to use the latest version.',
        title='Model',
    )
    schema_: str = Field(
        ...,
        alias='schema',
        description='JSON schema for field extraction. This schema determines what key-values pairs are extracted from the Markdown. The schema must be a valid JSON object and will be validated before processing the document.',
        title='Schema',
    )
    strict: Optional[bool] = Field(
        False,
        description='If True, reject schemas with unsupported fields (HTTP 422). If False, prune unsupported fields and continue. Only applies to extract versions that support schema validation.',
        title='Strict',
    )


class ExtractWarningCode(Enum):
    nonconformant_schema = 'nonconformant_schema'
    nonconformant_output = 'nonconformant_output'


class GroundingType(Enum):
    chunkLogo = 'chunkLogo'
    chunkCard = 'chunkCard'
    chunkAttestation = 'chunkAttestation'
    chunkScanCode = 'chunkScanCode'
    chunkForm = 'chunkForm'
    chunkTable = 'chunkTable'
    chunkFigure = 'chunkFigure'
    chunkText = 'chunkText'
    chunkMarginalia = 'chunkMarginalia'
    chunkTitle = 'chunkTitle'
    chunkPageHeader = 'chunkPageHeader'
    chunkPageFooter = 'chunkPageFooter'
    chunkPageNumber = 'chunkPageNumber'
    chunkKeyValue = 'chunkKeyValue'
    table = 'table'
    tableCell = 'tableCell'


class JobCreationResponse(BaseModel):
    job_id: str = Field(..., title='Job Id')


class JobSummary(BaseModel):
    """
    Summary of a job for listing.
    """

    created_at: Optional[int] = Field(
        0,
        description='Unix timestamp (seconds) for when the job was created. Mirrors received_at; exposed so clients have an explicit creation time.',
        title='Created At',
    )
    failure_reason: Optional[str] = Field(None, title='Failure Reason')
    job_id: str = Field(..., title='Job Id')
    progress: float = Field(
        ...,
        description='Job completion as a decimal from 0 (not started) to 1 (complete).',
        ge=0.0,
        le=1.0,
        title='Progress',
    )
    received_at: int = Field(..., title='Received At')
    status: str = Field(..., title='Status')


class JobsListResponse(BaseModel):
    """
    Response for listing jobs.
    """

    has_more: Optional[bool] = Field(False, title='Has More')
    jobs: list[JobSummary] = Field(..., title='Jobs')
    org_id: Optional[str] = Field(None, title='Org Id')


class ParseGroundingBox(BaseModel):
    bottom: float = Field(..., title='Bottom')
    left: float = Field(..., title='Left')
    right: float = Field(..., title='Right')
    top: float = Field(..., title='Top')


class ParseMetadata(BaseModel):
    credit_usage: float = Field(..., title='Credit Usage')
    duration_ms: int = Field(..., title='Duration Ms')
    failed_pages: Optional[list[int]] = Field(None, title='Failed Pages')
    filename: str = Field(..., title='Filename')
    job_id: str = Field(..., title='Job Id')
    org_id: Optional[str] = Field(..., title='Org Id')
    page_count: int = Field(..., title='Page Count')
    version: Optional[str] = Field(..., title='Version')


class ParseResponseTableCellGroundingPosition(BaseModel):
    chunk_id: str = Field(..., title='Chunk Id')
    col: int = Field(..., title='Col')
    colspan: int = Field(..., title='Colspan')
    row: int = Field(..., title='Row')
    rowspan: int = Field(..., title='Rowspan')


class ParseSplit(BaseModel):
    chunks: list[str] = Field(..., title='Chunks')
    class_: str = Field(..., alias='class', title='Class')
    identifier: str = Field(..., title='Identifier')
    markdown: str = Field(..., title='Markdown')
    pages: list[int] = Field(..., title='Pages')


class Patch(BaseModel):
    confidence: float = Field(..., title='Confidence')
    span: list[Any] = Field(..., max_length=2, min_length=2, title='Span')
    text: str = Field(..., title='Text')


class SectionMetadata(BaseModel):
    """
    Public metadata for section response.
    """

    credit_usage: float = Field(..., title='Credit Usage')
    duration_ms: int = Field(..., title='Duration Ms')
    filename: str = Field(..., title='Filename')
    job_id: Optional[str] = Field('', title='Job Id')
    org_id: Optional[str] = Field(None, title='Org Id')
    version: Optional[str] = Field(None, title='Version')


class SectionRequest(BaseModel):
    """
    Request model for section endpoint.
    """

    guidelines: Optional[str] = Field(
        None,
        description="Natural-language instructions to control hierarchy. Examples: 'Group by topic', 'Treat each numbered section as a top-level entry'.",
        title='Guidelines',
    )
    markdown: Optional[Union[bytes, str]] = Field(
        None,
        description="Parsed markdown with reference anchors (<a id='...'></a>). This is the markdown field from a parse response.",
        title='Markdown',
    )
    markdown_url: Optional[str] = Field(
        None, description='URL to fetch the markdown from.', title='Markdown Url'
    )
    model: Optional[str] = Field(
        None, description='Section model version. Defaults to latest.', title='Model'
    )


class SectionTOCEntry(BaseModel):
    """
    A single entry in the flat table of contents.
    """

    level: int = Field(..., title='Level')
    section_number: str = Field(..., title='Section Number')
    start_reference: str = Field(..., title='Start Reference')
    title: str = Field(..., title='Title')


class SplitClass(BaseModel):
    """
    Model for split classification option.
    """

    description: Optional[str] = Field(
        None,
        description='Detailed description of what this split type represents',
        title='Description',
    )
    identifier: Optional[str] = Field(
        None,
        description='Identifier to partition/group the splits by',
        title='Identifier',
    )
    name: str = Field(
        ..., description='Name of the split classification type', title='Name'
    )


class SplitData(BaseModel):
    """
    Split data for split classification endpoint.
    """

    classification: str = Field(..., title='Classification')
    identifier: Optional[str] = Field(..., title='Identifier')
    markdowns: list[str] = Field(..., title='Markdowns')
    pages: list[int] = Field(..., title='Pages')


class SplitMetadata(BaseModel):
    """
    Metadata for split classification response.
    """

    credit_usage: float = Field(..., title='Credit Usage')
    duration_ms: int = Field(..., title='Duration Ms')
    filename: str = Field(..., title='Filename')
    job_id: Optional[str] = Field(
        '', description='Inference history job ID', title='Job Id'
    )
    org_id: Optional[str] = Field(None, description='Organization ID', title='Org Id')
    page_count: int = Field(..., title='Page Count')
    version: Optional[str] = Field(
        None, description='Model version used for split classification', title='Version'
    )


class SplitRequest(BaseModel):
    """
    Request model for split classification endpoint.
    """

    markdown: Optional[Union[bytes, str]] = Field(
        None,
        description='The Markdown file or Markdown content to split.',
        title='Markdown',
    )
    markdown_url: Optional[str] = Field(
        None, description='The URL to the Markdown file to split.', title='Markdown Url'
    )
    model: Optional[str] = Field(
        'split-20251105',
        description='Model version to use for split classification. Defaults to the latest version.',
        title='Model',
    )
    split_class: list[SplitClass] = Field(
        ...,
        description='List of split classification options/configuration. Can be provided as JSON string in form data.',
        title='Split Class',
    )


class SplitResponse(BaseModel):
    """
    Response model for split classification endpoint.
    """

    metadata: SplitMetadata
    splits: list[SplitData] = Field(..., title='Splits')


class SplitType(Enum):
    page = 'page'


class SpreadsheetParseMetadata(BaseModel):
    """
    Metadata for spreadsheet parsing result.
    """

    credit_usage: Optional[float] = Field(
        0.0, description='Credits charged', title='Credit Usage'
    )
    duration_ms: int = Field(
        ..., description='Processing duration in milliseconds', title='Duration Ms'
    )
    filename: str = Field(..., description='Original filename', title='Filename')
    job_id: Optional[str] = Field(
        '', description='Inference history job ID', title='Job Id'
    )
    org_id: Optional[str] = Field(None, description='Organization ID', title='Org Id')
    sheet_count: int = Field(
        ..., description='Number of sheets processed', title='Sheet Count'
    )
    total_cells: int = Field(
        ..., description='Total non-empty cells across all sheets', title='Total Cells'
    )
    total_chunks: int = Field(
        ...,
        description='Total chunks (tables + images) extracted',
        title='Total Chunks',
    )
    total_images: Optional[int] = Field(
        0, description='Total images extracted', title='Total Images'
    )
    total_rows: int = Field(
        ..., description='Total rows across all sheets', title='Total Rows'
    )
    version: Optional[str] = Field(
        None, description='Model version for parsing images', title='Version'
    )


class SpreadsheetSplit(BaseModel):
    """
    Sheet-based split from spreadsheet parsing.

    Similar to ParseSplit but grouped by sheet instead of page.
    Supports both 'page' (per-sheet) and 'full' (all sheets) split types.
    """

    chunks: list[str] = Field(
        ..., description='Chunk IDs in this split', title='Chunks'
    )
    class_: str = Field(
        ...,
        alias='class',
        description="Split class: 'page' for per-sheet splits, 'full' for single split with all content",
        title='Class',
    )
    identifier: str = Field(
        ...,
        description="Split identifier: sheet name for 'page' splits, 'full' for full split",
        title='Identifier',
    )
    markdown: str = Field(
        ..., description='Combined markdown for this split', title='Markdown'
    )
    sheets: list[int] = Field(
        ...,
        description="Sheet indices: single element for 'page' splits, all indices for 'full' split",
        title='Sheets',
    )


class ValidationError(BaseModel):
    loc: list[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class Status(Enum):
    """
    Filter by job status.
    """

    cancelled = 'cancelled'
    completed = 'completed'
    failed = 'failed'
    pending = 'pending'
    processing = 'processing'


class V1AdeExtractJobsGetParametersQuery(BaseModel):
    page: Optional[int] = Field(
        0, description='Page number (0-indexed)', ge=0, title='Page'
    )
    pageSize: Optional[int] = Field(
        10, description='Number of items per page', ge=1, le=100, title='Pagesize'
    )
    status: Optional[Status] = Field(
        None, description='Filter by job status.', title='Status'
    )


class V1AdeParseJobsGetParametersQuery(BaseModel):
    page: Optional[int] = Field(
        0, description='Page number (0-indexed)', ge=0, title='Page'
    )
    pageSize: Optional[int] = Field(
        10, description='Number of items per page', ge=1, le=100, title='Pagesize'
    )
    status: Optional[Status] = Field(
        None, description='Filter by job status.', title='Status'
    )


class AsyncParseRequestWithEncryptedPassword(BaseModel):
    custom_prompts: Optional[str] = Field(
        None,
        description='Optional JSON string mapping chunk types to custom parsing prompts. Only the `figure` key is supported, for example \'{"figure":"Describe axis labels in detail."}\'.',
        title='Custom Prompts',
    )
    document: Optional[bytes] = Field(
        None,
        description='A file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document_url` parameter must be provided.',
        title='Document',
    )
    document_url: Optional[str] = Field(
        None,
        description='The URL to the file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document` parameter must be provided.',
        title='Document Url',
    )
    model: Optional[str] = Field(
        None, description='The version of the model to use for parsing.', title='Model'
    )
    output_save_url: Optional[str] = Field(
        None,
        description='If zero data retention (ZDR) is enabled, you must enter a URL for the parsed output to be saved to. When ZDR is enabled, the parsed content will not be in the API response.',
        title='Output Save Url',
    )
    password: Optional[str] = Field(
        None,
        description='Password for encrypted document files. If the document is password-protected, provide the password to decrypt and process the document. Ignored for unencrypted documents.',
        title='Password',
    )
    split: Optional[SplitType] = Field(
        None,
        description='If you want to split documents into smaller sections, include the split parameter. Set the parameter to page to split documents at the page level. The splits object in the API output will contain a set of data for each page.',
    )


class ExtractWarning(BaseModel):
    code: ExtractWarningCode = Field(
        ...,
        description='The type of warning, used to translate to a status code downstream',
    )
    msg: str = Field(
        ...,
        description='Human-readable description of the warning with more details',
        title='Msg',
    )


class HTTPValidationError(BaseModel):
    detail: Optional[list[ValidationError]] = Field(None, title='Detail')


class ParseGrounding(BaseModel):
    box: ParseGroundingBox
    page: int = Field(..., title='Page')


class ParseRequestWithEncryptedPassword(BaseModel):
    custom_prompts: Optional[str] = Field(
        None,
        description='Optional JSON string mapping chunk types to custom parsing prompts. Only the `figure` key is supported, for example \'{"figure":"Describe axis labels in detail."}\'.',
        title='Custom Prompts',
    )
    document: Optional[bytes] = Field(
        None,
        description='A file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document_url` parameter must be provided.',
        title='Document',
    )
    document_url: Optional[str] = Field(
        None,
        description='The URL to the file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document` parameter must be provided.',
        title='Document Url',
    )
    model: Optional[str] = Field(
        None, description='The version of the model to use for parsing.', title='Model'
    )
    password: Optional[str] = Field(
        None,
        description='Password for encrypted document files. If the document is password-protected, provide the password to decrypt and process the document. Ignored for unencrypted documents.',
        title='Password',
    )
    split: Optional[SplitType] = Field(
        None,
        description='If you want to split documents into smaller sections, include the split parameter. Set the parameter to page to split documents at the page level. The splits object in the API output will contain a set of data for each page.',
    )


class ParseResponseGrounding(BaseModel):
    box: ParseGroundingBox
    confidence: Optional[float] = Field(None, title='Confidence')
    low_confidence_spans: Optional[list[Patch]] = Field(
        None, title='Low Confidence Spans'
    )
    page: int = Field(..., title='Page')
    type: GroundingType


class ParseResponseTableCellGrounding(BaseModel):
    box: ParseGroundingBox
    confidence: Optional[float] = Field(None, title='Confidence')
    page: int = Field(..., title='Page')
    position: Optional[ParseResponseTableCellGroundingPosition] = None
    type: GroundingType


class SectionResponse(BaseModel):
    """
    Response model for section endpoint.
    """

    metadata: SectionMetadata
    table_of_contents: list[SectionTOCEntry] = Field(..., title='Table Of Contents')
    table_of_contents_md: str = Field(..., title='Table Of Contents Md')


class SpreadsheetChunk(BaseModel):
    """
    Chunk from spreadsheet parsing.

    Can represent:
    - Table chunks from spreadsheet cells
    - Parsed content chunks from embedded images (text, table, figure, etc.)
    """

    grounding: Optional[ParseGrounding] = Field(
        None,
        description='Visual grounding coordinates from /parse API (only for chunks derived from embedded images)',
    )
    id: str = Field(
        ...,
        description="Chunk ID - format: '{sheet_name}-{cell_range}' for tables, '{sheet_name}-image-{index}-{anchor_cell}-chunk-{i}-{type}' for parsed image chunks",
        title='Id',
    )
    markdown: str = Field(
        ...,
        description='Chunk content as HTML table with anchor tag (for tables) or parsed markdown content (for chunks from images)',
        title='Markdown',
    )
    type: str = Field(
        ...,
        description="Chunk type: 'table' for spreadsheet tables, or types from /parse (text, table, figure, form, etc.) for chunks derived from embedded images",
        title='Type',
    )


class SpreadsheetParseResponse(BaseModel):
    """
    Response from /ade/parse-spreadsheet endpoint.

    Similar structure to ParseResponse but without grounding.
    """

    chunks: list[SpreadsheetChunk] = Field(
        ..., description='List of table chunks (HTML)', title='Chunks'
    )
    markdown: str = Field(
        ...,
        description='Full document as HTML with anchor tags and tables',
        title='Markdown',
    )
    metadata: SpreadsheetParseMetadata = Field(..., description='Parsing metadata')
    splits: list[SpreadsheetSplit] = Field(
        ..., description='Sheet-based splits', title='Splits'
    )


class BuildSchemaMetadata(BaseModel):
    credit_usage: Optional[float] = Field(0.0, title='Credit Usage')
    duration_ms: Optional[int] = Field(0, title='Duration Ms')
    filename: Optional[str] = Field(None, title='Filename')
    job_id: Optional[str] = Field('', title='Job Id')
    org_id: Optional[str] = Field(None, title='Org Id')
    version: Optional[str] = Field(None, title='Version')
    warnings: Optional[list[ExtractWarning]] = Field(
        None,
        description="Structured warnings from the extraction process. Each warning is an instance of ExtractWarning with 'code' (e.g. 'nonconformant_schema') and 'msg' (human-readable description). Present only for extract versions from extract-20260314 and above that support structured warnings.",
        title='Warnings',
    )


class BuildSchemaResponse(BaseModel):
    extraction_schema: str = Field(
        ...,
        description='The generated JSON schema as a string.',
        title='Extraction Schema',
    )
    metadata: BuildSchemaMetadata = Field(
        ..., description='The metadata for the schema generation process.'
    )


class ExtractMetadata(BaseModel):
    credit_usage: float = Field(..., title='Credit Usage')
    duration_ms: int = Field(..., title='Duration Ms')
    fallback_model_version: Optional[str] = Field(
        None,
        description='The extract model that was actually used to extract the data when the initial extraction attempt failed with the requested version.',
        title='Fallback Model Version',
    )
    filename: str = Field(..., title='Filename')
    job_id: str = Field(..., title='Job Id')
    org_id: Optional[str] = Field(..., title='Org Id')
    schema_violation_error: Optional[str] = Field(
        None,
        description='A detailed error message shows why the extracted data does not fully conform to the input schema. Null means the extraction result is consistent with the input schema.',
        title='Schema Violation Error',
    )
    version: Optional[str] = Field(..., title='Version')
    warnings: Optional[list[ExtractWarning]] = Field(
        None,
        description="Structured warnings from the extraction process. Each warning is an instance of ExtractWarning with 'code' (e.g. 'nonconformant_schema') and 'msg' (human-readable description). Present only for extract versions from extract-20260314 and above that support structured warnings.",
        title='Warnings',
    )


class ExtractResponse(BaseModel):
    extraction: dict[str, Any] = Field(
        ..., description='The extracted key-value pairs.', title='Extraction'
    )
    extraction_metadata: dict[str, Any] = Field(
        ...,
        description='The extracted key-value pairs and the chunk_reference for each one.',
        title='Extraction Metadata',
    )
    metadata: ExtractMetadata = Field(
        ..., description='The metadata for the extraction process.'
    )


class ParseChunk(BaseModel):
    grounding: ParseGrounding
    id: str = Field(..., title='Id')
    markdown: str = Field(..., title='Markdown')
    type: str = Field(..., title='Type')


class ParseResponse(BaseModel):
    chunks: list[ParseChunk] = Field(..., title='Chunks')
    grounding: Optional[
        dict[str, Union[ParseResponseGrounding, ParseResponseTableCellGrounding]]
    ] = Field(None, title='Grounding')
    markdown: str = Field(..., title='Markdown')
    metadata: ParseMetadata
    splits: list[ParseSplit] = Field(..., title='Splits')


class ExtractJobStatusResponse(BaseModel):
    """
    The status of an extract job, plus the results once it completes.
    """

    created_at: Optional[int] = Field(
        0,
        description='Unix timestamp (in seconds) for when the job was created.',
        title='Created At',
    )
    data: Optional[ExtractResponse] = Field(
        None,
        description='The extraction results, returned here when the job is complete and you did not set an `output_save_url`. Large results are returned through `output_url` instead.',
    )
    failure_reason: Optional[str] = Field(
        None,
        description='If the job failed, a message describing what went wrong.',
        title='Failure Reason',
    )
    job_id: str = Field(
        ..., description='A unique identifier for this extract job.', title='Job Id'
    )
    metadata: Optional[ExtractMetadata] = Field(
        None,
        description='Information about the extraction, such as the model version, duration, credit usage, and any schema warnings.',
    )
    org_id: Optional[str] = Field(None, description='Organization ID.', title='Org Id')
    output_url: Optional[str] = Field(
        None,
        description='A URL to download the extraction results. Provided when the job is complete and either you set an `output_save_url` or the result is larger than 1 MB. URLs for large results are temporary and expire one hour after you request the job.',
        title='Output Url',
    )
    progress: float = Field(
        ...,
        description='Job completion. Either 0.0 (not yet complete) or 1.0 (complete).',
        ge=0.0,
        le=1.0,
        title='Progress',
    )
    received_at: int = Field(
        ...,
        description='Unix timestamp (in seconds) for when the job was received.',
        title='Received At',
    )
    status: str = Field(
        ...,
        description='The current state of the job: `pending`, `processing`, `completed`, `failed`, or `cancelled`.',
        title='Status',
    )
    version: Optional[str] = Field(
        None,
        description='The exact model snapshot used for the extraction.',
        title='Version',
    )


class JobStatusResponse(BaseModel):
    """
    Unified response for job status endpoint.
    """

    created_at: Optional[int] = Field(
        0,
        description='Unix timestamp (seconds) for when the job was created. Mirrors received_at; exposed so clients have an explicit creation time.',
        title='Created At',
    )
    data: Optional[Union[ParseResponse, SpreadsheetParseResponse]] = Field(
        None,
        description='The parsed output (ParseResponse for documents, SpreadsheetParseResponse for spreadsheets), if the job is complete and the `output_save_url` parameter was not used.',
        title='Data',
    )
    failure_reason: Optional[str] = Field(None, title='Failure Reason')
    job_id: str = Field(..., title='Job Id')
    metadata: Optional[ParseMetadata] = None
    org_id: Optional[str] = Field(None, title='Org Id')
    output_url: Optional[str] = Field(
        None,
        description='The URL to the parsed content. This field contains a URL when the job is complete and either you specified the `output_save_url` parameter or the result is larger than 1MB. When the result exceeds 1MB, the URL is a presigned S3 URL that expires after 1 hour. Each time you GET the job, a new presigned URL is generated.',
        title='Output Url',
    )
    progress: float = Field(
        ...,
        description='Job completion progress as a decimal from 0 to 1, where 0 is not started, 1 is finished, and values between 0 and 1 indicate work in progress.',
        ge=0.0,
        le=1.0,
        title='Progress',
    )
    received_at: int = Field(..., title='Received At')
    status: str = Field(..., title='Status')
    version: Optional[str] = Field(None, title='Version')
