# generated by datamodel-codegen:
#   filename:  v2-aide.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, Field


class BaseElementOptions(BaseModel):
    caption: Optional[bool] = Field(True, title='Caption')


class BodyStageFileV1FilesPost(BaseModel):
    file: str = Field(..., title='File')


class Type(Enum):
    """
    The element type. Determines which optional fields appear on this element.
    """

    text = 'text'
    table = 'table'
    table_cell = 'table_cell'
    figure = 'figure'
    marginalia = 'marginalia'
    attestation = 'attestation'
    logo = 'logo'
    card = 'card'
    scan_code = 'scan_code'


class Element(BaseModel):
    """
    Hierarchical document element. All non-page elements share this shape.

    Keys off `type`; optional fields are excluded from the serialized JSON
    via ``exclude_none=True`` when not set.
    """

    children: Optional[list[Element]] = Field(
        None,
        description='The cells (`table_cell` elements) of a `table` element. Present only when `type` is `table`.',
        title='Children',
    )
    col: Optional[int] = Field(
        None,
        description='0-indexed column position of this cell within its parent `table`. Present only on `table_cell` elements.',
        title='Col',
    )
    colspan: Optional[int] = Field(
        None,
        description='Number of columns this cell spans. `1` for unmerged cells. Present only on `table_cell` elements.',
        title='Colspan',
    )
    id: str = Field(
        ...,
        description="A unique identifier for this element within the document. Use it to look up the element's entry in the top-level `grounding` map; treat the value as opaque.",
        title='Id',
    )
    row: Optional[int] = Field(
        None,
        description='0-indexed row position of this cell within its parent `table`. Present only on `table_cell` elements.',
        title='Row',
    )
    rowspan: Optional[int] = Field(
        None,
        description='Number of rows this cell spans. `1` for unmerged cells. Present only on `table_cell` elements.',
        title='Rowspan',
    )
    span: list[Any] = Field(
        ...,
        description='Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this element.',
        max_length=2,
        min_length=2,
        title='Span',
    )
    type: Type = Field(
        ...,
        description='The element type. Determines which optional fields appear on this element.',
        title='Type',
    )


class FigureOptions(BaseModel):
    caption: Optional[bool] = Field(True, title='Caption')


class Type1(Enum):
    """
    The element type. Matches the same element's `type` in the `structure` tree.
    """

    text = 'text'
    table = 'table'
    table_cell = 'table_cell'
    figure = 'figure'
    marginalia = 'marginalia'
    attestation = 'attestation'
    logo = 'logo'
    card = 'card'
    scan_code = 'scan_code'


class GroundingEntry(BaseModel):
    """
    One fine-grained grounding segment (line-level or finer).
    """

    box: list[Any] = Field(
        ...,
        description='Bounding box `[left, top, right, bottom]` for this part on the source page, in pixels.',
        max_length=4,
        min_length=4,
        title='Box',
    )
    span: list[Any] = Field(
        ...,
        description='Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this part.',
        max_length=2,
        min_length=2,
        title='Span',
    )


class GroundingOptions(BaseModel):
    parts: Optional[bool] = Field(True, title='Parts')


class Status(Enum):
    """
    Whether this page was parsed successfully (`ok`) or failed (`failed`).
    """

    ok = 'ok'
    failed = 'failed'


class Page(BaseModel):
    children: Optional[list[Element]] = Field(
        None,
        description='The elements detected on this page, in reading order.',
        title='Children',
    )
    dpi: Optional[int] = Field(
        None,
        description="DPI used to scale this page's PDF coordinates to pixels (pixels = PDF_points × dpi / 72). Present only for pages that originated from a PDF; omitted for image-input pages (which have no DPI concept — their coordinates are already pixels relative to the original upload) and for pages with `status` `failed`.",
        title='Dpi',
    )
    height: Optional[int] = Field(
        None,
        description='Page height in pixels. Omitted when `status` is `failed`.',
        title='Height',
    )
    page: int = Field(
        ...,
        description='The 0-indexed page number in the source document. Not contiguous when `options.pages` filters out some pages.',
        title='Page',
    )
    reason: Optional[str] = Field(
        None,
        description='Failure reason. Present only when `status` is `failed`.',
        title='Reason',
    )
    span: list[Any] = Field(
        ...,
        description='Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this page. Zero-length `[n, n]` for failed pages.',
        max_length=2,
        min_length=2,
        title='Span',
    )
    status: Optional[Status] = Field(
        'ok',
        description='Whether this page was parsed successfully (`ok`) or failed (`failed`).',
        title='Status',
    )
    type: Literal['page'] = Field(
        'page',
        description='The node type. Identifies this node as a page in the structure tree.',
        title='Type',
    )
    width: Optional[int] = Field(
        None,
        description='Page width in pixels. Omitted when `status` is `failed`.',
        title='Width',
    )


class ServiceTier(Enum):
    """
    The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).
    """

    standard = 'standard'
    priority = 'priority'


class ParseBilling(BaseModel):
    """
    Billing summary for one parse request.
    """

    service_tier: Optional[ServiceTier] = Field(
        ...,
        description='The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).',
        title='Service Tier',
    )
    total_credits: Optional[float] = Field(
        ..., description='Credits charged for this request.', title='Total Credits'
    )


class ParseMetadata(BaseModel):
    """
    Information about a parse request. This is the customer-facing shape —
    the internal billing-canonical metadata (``aide_common.parse_schema.ParseMetadata``)
    is projected into it at the render boundary (``project_customer_metadata``).
    """

    billing: ParseBilling = Field(
        ..., description='Billing summary: the service tier and the credits charged.'
    )
    duration_ms: Optional[int] = Field(
        ..., description='Total processing time in milliseconds.', title='Duration Ms'
    )
    failed_pages: list[int] = Field(
        ...,
        description='0-indexed page numbers that failed to parse. Empty when all pages succeed; failed pages also appear in `structure.children` with `status: failed`.',
        title='Failed Pages',
    )
    job_id: Optional[str] = Field(
        ...,
        description="The parse job identifier — always server-minted and unique per submit. On the async `/jobs` route this is the id the caller polls. Correlates with the job's entry in your billing dashboard.",
        title='Job Id',
    )
    markdown_chars: Optional[int] = Field(
        ...,
        description='Number of Unicode code points in the returned `markdown` string.',
        title='Markdown Chars',
    )
    model_version: Optional[str] = Field(
        ...,
        description='The exact model snapshot that parsed the document, e.g. `dpt-3-pro-20260710`.',
        title='Model Version',
    )
    page_count: Optional[int] = Field(
        ...,
        description='Total number of pages in the source document. Includes pages filtered out by `options.pages`; the actual returned pages are in `structure.children`.',
        title='Page Count',
    )


class Format(Enum):
    markdown = 'markdown'
    html = 'html'


class TableOptions(BaseModel):
    caption: Optional[bool] = Field(True, title='Caption')
    format: Optional[Format] = Field('html', title='Format')


class V2Billing(BaseModel):
    """
    Billing summary: the service tier the request ran in and the credits
    charged.
    """

    service_tier: Optional[ServiceTier] = Field(
        None,
        description='The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).',
        title='Service Tier',
    )
    total_credits: Optional[float] = Field(
        None, description='Credits charged for this request.', title='Total Credits'
    )


class V2ExtractMetadata(BaseModel):
    """
    Response metadata for a v2 extract call.
    """

    billing: Optional[V2Billing] = Field(
        None,
        description='Billing summary: the service tier the request ran in and the credits charged.',
    )
    credit_usage: Optional[float] = Field(
        0.0, description='Credits billed for this request.', title='Credit Usage'
    )
    doc_id: Optional[str] = Field(
        None,
        description='Present when the input markdown contained a ``<!-- doc_id=<id> -->`` comment (embedded by ``POST /v2/parse``). Links this extract call to the originating parse job.',
        title='Doc Id',
    )
    duration_ms: int = Field(
        ...,
        description='End-to-end request duration in milliseconds.',
        title='Duration Ms',
    )
    job_id: str = Field(
        ...,
        description='Gateway job id (workflow id). Matches the ``x-request-id`` the gateway minted for this request and the billing row id in vision-agent.',
        title='Job Id',
    )
    version: str = Field(..., description='Resolved model version.', title='Version')


class V2ExtractOptions(BaseModel):
    """
    Extraction options (``docs/extract-v2-proposal.md`` → Options).
    """

    strict: Optional[bool] = Field(
        False,
        description='When ``true``, returns HTTP 422 if the schema contains fields the model cannot extract. When ``false`` (default), unsupported fields are skipped and extraction continues.',
        title='Strict',
    )


class V2WorkflowMetadata(BaseModel):
    """
    Response metadata for a v2 workflow call
    (``docs/pipeline-v2-proposal.md`` → Top-level metadata).
    """

    billing: Optional[V2Billing] = Field(
        None,
        description='Billing summary: the service tier the request ran in and the credits charged.',
    )
    credit_usage: Optional[float] = Field(
        0.0,
        description='Combined credits billed for this request (parse + extract).',
        title='Credit Usage',
    )
    duration_ms: int = Field(
        ...,
        description='Total end-to-end duration across all stages in milliseconds.',
        title='Duration Ms',
    )
    job_id: str = Field(
        ..., description='Gateway job id (workflow id).', title='Job Id'
    )


class ValidationError(BaseModel):
    ctx: Optional[dict[str, Any]] = Field(None, title='Context')
    input: Optional[Any] = Field(None, title='Input')
    loc: list[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class WorkflowDocumentInput(BaseModel):
    """
    One declared document input in the ``inputs`` map.

    A caller supplies exactly one of ``document`` or ``document_url``:

    * ``document`` — name of a multipart form part carrying the raw bytes. The
      gateway stages those bytes internally before the workflow runs.
    * ``document_url`` — public URL (SSRF-validated at submit; fetched and staged
      by the gateway before the workflow starts).
    """

    document: Optional[str] = Field(
        None,
        description='Name of the multipart form part carrying the document bytes. The gateway resolves this to an internal ref before validation; it is not stored in the final request object.',
        examples=['report_pdf'],
        title='Document',
    )
    document_url: Optional[str] = Field(
        None,
        description='URL to fetch the document from. Must be a public http(s) URL; private/loopback IPs are rejected at submit time.',
        title='Document Url',
    )


class WorkflowStepOptions(BaseModel):
    """
    Unified options for the ``parse-extract`` prebuilt step.

    ``pages`` applies to the parse stage; ``strict`` applies to the extract
    stage. Omit entirely to use each stage's defaults.
    """

    pages: Optional[list[int]] = Field(
        None,
        description='0-indexed page indices to process. ``null`` = all pages. Negative indices are rejected; indices ≥ page_count are silently ignored.',
        title='Pages',
    )
    strict: Optional[bool] = Field(
        False,
        description='When ``true``, returns 422 if the schema contains fields the model cannot extract. When ``false``, unsupported fields are skipped.',
        title='Strict',
    )


class BlocksOptions(BaseModel):
    attestation: Optional[BaseElementOptions] = None
    card: Optional[BaseElementOptions] = None
    figure: Optional[FigureOptions] = None
    logo: Optional[BaseElementOptions] = None
    marginalia: Optional[BaseElementOptions] = None
    scan_code: Optional[BaseElementOptions] = None
    table: Optional[TableOptions] = None
    text: Optional[BaseElementOptions] = None


class Document(BaseModel):
    children: Optional[list[Page]] = Field(
        None,
        description='The pages of the document, in source order.',
        title='Children',
    )
    type: Literal['document'] = Field(
        'document',
        description='The node type. Identifies this node as the root of the structure tree.',
        title='Type',
    )


class GroundingElement(BaseModel):
    """
    Spatial grounding for one document element.

    Mirrors the element's node in the `structure` tree (same `id`, same `span`)
    and layers the spatial data on top: the element-level bounding box, its
    fine-grained `parts`, and — for a `table` — its cells nested as `children`.
    """

    box: list[Any] = Field(
        ...,
        description='Bounding box `[left, top, right, bottom]` for the full element on the source page, in pixels.',
        max_length=4,
        min_length=4,
        title='Box',
    )
    children: Optional[list[GroundingElement]] = Field(
        None,
        description="The cells (`table_cell` grounding nodes) of a `table` element, mirroring the table's `children` in the `structure` tree. Present only when `type` is `table`.",
        title='Children',
    )
    id: str = Field(
        ...,
        description="The element's unique identifier within the document. Matches the same element's `id` in the `structure` tree.",
        title='Id',
    )
    parts: Optional[list[GroundingEntry]] = Field(
        None,
        description='Finer-grained grounding segments within the element. Per visual line for `text` and `marginalia`; empty for other element types or when `options.grounding.parts` is `false`.',
        title='Parts',
    )
    span: list[Any] = Field(
        ...,
        description="Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this element. Matches the element's `span` in the `structure` tree.",
        max_length=2,
        min_length=2,
        title='Span',
    )
    type: Type1 = Field(
        ...,
        description="The element type. Matches the same element's `type` in the `structure` tree.",
        title='Type',
    )


class GroundingPage(BaseModel):
    """
    A page node in the `grounding` tree, mirroring the page in `structure`.
    """

    children: Optional[list[GroundingElement]] = Field(
        None,
        description="Grounding for the elements on this page, in reading order — the same order and `id`s as the page's `children` in the `structure` tree. Empty for failed pages.",
        title='Children',
    )
    page: int = Field(
        ...,
        description="The 0-indexed page number in the source document. Matches the page's `page` in the `structure` tree.",
        title='Page',
    )
    span: list[Any] = Field(
        ...,
        description='Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this page. Zero-length `[n, n]` for failed pages.',
        max_length=2,
        min_length=2,
        title='Span',
    )
    type: Literal['page'] = Field(
        'page',
        description='The node type. Identifies this node as a page in the grounding tree.',
        title='Type',
    )


class HTTPValidationError(BaseModel):
    detail: Optional[list[ValidationError]] = Field(None, title='Detail')


class PrebuiltWorkflowStep(BaseModel):
    """
    A Phase 1 step: references a server-defined pipeline by name.

    The ``name`` identifies the prebuilt pipeline to run AND becomes the key
    under which this step's result appears in the response ``output`` map.
    The ``document`` field is a reference into the ``inputs`` namespace
    (``"$inputs.<logical-name>"``).
    """

    document: str = Field(
        ...,
        description='Reference into the ``inputs`` namespace, e.g. ``"$inputs.report"``. The referenced input must be declared in the ``inputs`` form field.',
        title='Document',
    )
    name: Literal['parse-extract'] = Field(
        ...,
        description='Workflow to run — doubles as the result key in ``output``. v1 only: ``"parse-extract"``.',
        title='Name',
    )
    options: Optional[WorkflowStepOptions] = Field(
        None, description='Parse + extract options for this step. Omit for defaults.'
    )
    schema_: dict[str, Any] = Field(
        ...,
        alias='schema',
        description='JSON Schema for fields to extract.',
        examples=[{'properties': {'revenue': {'type': 'string'}}, 'type': 'object'}],
        title='Schema',
    )


class GroundingDocument(BaseModel):
    """
    Root of the `grounding` tree. Mirrors the hierarchy of `structure`
    (`document → page → element → table_cell`), carrying the spatial data
    (`box`, `parts`) that `structure` deliberately omits.
    """

    children: Optional[list[GroundingPage]] = Field(
        None,
        description='The pages of the document, in source order — the same order as `structure.children`.',
        title='Children',
    )
    type: Literal['document'] = Field(
        'document',
        description='The node type. Identifies this node as the root of the grounding tree.',
        title='Type',
    )


class ParseResponse(BaseModel):
    """
    The parse result: the full document as `markdown`, its hierarchical
    `structure`, per-element spatial `grounding`, and request `metadata`.
    """

    grounding: GroundingDocument = Field(
        ...,
        description="The document's spatial grounding, as a tree mirroring `structure` (`document → page → element → table_cell`). Each element node carries the same `id` and `span` as in `structure`, plus its bounding box and finer-grained parts.",
    )
    markdown: str = Field(
        ...,
        description='The full document as a single Markdown string, in reading order.',
        title='Markdown',
    )
    metadata: ParseMetadata = Field(
        ...,
        description='Information about the request: model version, page count, duration, billing, and more.',
    )
    structure: Document = Field(
        ...,
        description="The document's hierarchical structure: pages and the elements detected on each page. Spatial information for each element is in `grounding`.",
    )


Element.model_rebuild()
GroundingElement.model_rebuild()
