# generated by datamodel-codegen:
#   filename:  v2-aide.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, Field, RootModel


class BaseElementOptions(BaseModel):
    markdown: Optional[bool] = Field(True, title='Markdown')


class BodyStageFileV1FilesPost(BaseModel):
    file: str = Field(..., title='File')


class Box(BaseModel):
    """
    Axis-aligned bounding box in normalized page coordinates.

    Every value is a fraction of the page's width (`xmin`/`xmax`) or height
    (`ymin`/`ymax`) in `[0, 1]`, with at most 8 decimal places. To convert to
    pixels, multiply by the dimensions of whatever raster of the page you are
    drawing on. Coordinates are clamped and rounded at construction so the
    in-process value always equals the serialized one.
    """

    xmax: float = Field(
        ...,
        description='Right edge as a fraction of the page width, in `[0, 1]`.',
        title='Xmax',
    )
    xmin: float = Field(
        ...,
        description='Left edge as a fraction of the page width, in `[0, 1]`.',
        title='Xmin',
    )
    ymax: float = Field(
        ...,
        description='Bottom edge as a fraction of the page height, in `[0, 1]`.',
        title='Ymax',
    )
    ymin: float = Field(
        ...,
        description='Top edge as a fraction of the page height, in `[0, 1]`.',
        title='Ymin',
    )


class Type(Enum):
    """
    The element type. Determines which optional fields appear on this element.
    """

    text = 'text'
    table = 'table'
    table_cell = 'table_cell'
    figure = 'figure'
    marginalia = 'marginalia'
    attestation = 'attestation'
    logo = 'logo'
    card = 'card'
    scan_code = 'scan_code'


class FigureOptions(BaseModel):
    markdown: Optional[bool] = Field(True, title='Markdown')


class Status(Enum):
    """
    Whether this page was parsed successfully (`ok`) or failed (`failed`).
    """

    ok = 'ok'
    failed = 'failed'


class ServiceTier(Enum):
    """
    The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).
    """

    standard = 'standard'
    priority = 'priority'


class ParseBilling(BaseModel):
    """
    Billing summary for one parse request.
    """

    service_tier: Optional[ServiceTier] = Field(
        ...,
        description='The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).',
        title='Service Tier',
    )
    total_credits: Optional[float] = Field(
        ..., description='Credits charged for this request.', title='Total Credits'
    )


class ParseMetadata(BaseModel):
    """
    Information about a parse request. This is the customer-facing shape —
    the internal billing-canonical metadata (``aide_common.parse_schema.ParseMetadata``)
    is projected into it at the render boundary (``project_customer_metadata``).
    """

    billing: ParseBilling = Field(
        ..., description='Billing summary: the service tier and the credits charged.'
    )
    duration_ms: Optional[int] = Field(
        ..., description='Total processing time in milliseconds.', title='Duration Ms'
    )
    failed_pages: list[int] = Field(
        ...,
        description='1-indexed page numbers that failed to parse. Empty when all pages succeed; failed pages also appear in `structure.children` with `status: failed`.',
        title='Failed Pages',
    )
    job_id: Optional[str] = Field(
        ...,
        description="The parse job identifier — always server-minted and unique per submit. On the async `/jobs` route this is the id the caller polls. Correlates with the job's entry in your billing dashboard. Format: ``<service>-<26-character Crockford base32 ULID>`` matching ``^(parse|extract)-[0-9a-hjkmnp-tv-z]{26}$``. Opaque, server-minted, and stable for the life of the job — the same id is returned on the sync response, the async 202, and every poll. Treat it as opaque; older id formats remain accepted indefinitely and are never re-issued.",
        title='Job Id',
    )
    model_version: Optional[str] = Field(
        ...,
        description='The exact model snapshot that parsed the document, e.g. `dpt-3-pro-20260710`.',
        title='Model Version',
    )
    openapi_spec: str = Field(
        ...,
        description='URL of the OpenAPI spec covering this API, for inspection and client generation.',
        title='Openapi Spec',
    )
    output_markdown_chars: Optional[int] = Field(
        ...,
        description='Number of Unicode code points in the returned `markdown` string.',
        title='Output Markdown Chars',
    )
    page_count: Optional[int] = Field(
        ...,
        description='Total number of pages in the source document. Includes pages filtered out by `options.pages`; the actual returned pages are in `structure.children`.',
        title='Page Count',
    )
    range_units: Literal['unicode_codepoints'] = Field(
        ...,
        description='Units of every `range` offset in the response. Always `"unicode_codepoints"` (Unicode code points into `markdown`). Declared explicitly so consumers know how to slice the string — e.g. JavaScript strings are UTF-16, so a naive `.slice()` drifts when the markdown contains astral characters; such consumers must convert code-point offsets to UTF-16 indices first.',
        title='Range Units',
    )


class Range(BaseModel):
    """
    A `[start, end)` slice of the top-level `markdown` string.
    """

    end: int = Field(
        ...,
        description='Exclusive end offset into the top-level `markdown` string, in the units declared by `metadata.range_units` (Unicode code points).',
        title='End',
    )
    start: int = Field(
        ...,
        description='Inclusive start offset into the top-level `markdown` string, in the units declared by `metadata.range_units` (Unicode code points).',
        title='Start',
    )


class Format(Enum):
    markdown = 'markdown'
    html = 'html'


class TableOptions(BaseModel):
    format: Optional[Format] = Field('html', title='Format')
    markdown: Optional[bool] = Field(True, title='Markdown')


class V2Billing(BaseModel):
    """
    Billing summary: the service tier the request ran in and the credits
    charged.
    """

    input_markdown_chars: Optional[int] = Field(
        None,
        description='Characters (Unicode code points) in the input markdown as submitted — the input basis of the credit charge. Extract responses only.',
        title='Input Markdown Chars',
    )
    output_extraction_chars: Optional[int] = Field(
        None,
        description='Characters in the serialized extraction output — the output basis of the credit charge. Extract responses only.',
        title='Output Extraction Chars',
    )
    service_tier: Optional[ServiceTier] = Field(
        None,
        description='The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).',
        title='Service Tier',
    )
    total_credits: Optional[float] = Field(
        None, description='Credits charged for this request.', title='Total Credits'
    )


class V2ExtractMetadata(BaseModel):
    """
    Response metadata for a v2 extract call.
    """

    billing: Optional[V2Billing] = Field(
        None,
        description='Billing summary: the service tier the request ran in and the credits charged.',
    )
    credit_usage: Optional[float] = Field(
        0.0, description='Credits billed for this request.', title='Credit Usage'
    )
    doc_id: Optional[str] = Field(
        None,
        description='Present when the input markdown contained a ``<!-- doc_id=<id> -->`` comment (embedded by ``POST /v2/parse``). Links this extract call to the originating parse job.',
        title='Doc Id',
    )
    duration_ms: int = Field(
        ...,
        description='End-to-end request duration in milliseconds.',
        title='Duration Ms',
    )
    job_id: str = Field(
        ...,
        description='Gateway job id (workflow id). Matches the ``x-request-id`` the gateway minted for this request and the billing row id in vision-agent.',
        title='Job Id',
    )
    model_version: str = Field(
        ..., description='Resolved model version.', title='Model Version'
    )
    openapi_spec: str = Field(
        ...,
        description='URL of the OpenAPI spec covering this API, for inspection and client generation.',
    )
    range_units: Literal['unicode_codepoints'] = Field(
        ...,
        description='Units of every `range` offset in the response. Always `"unicode_codepoints"` (Unicode code points into `markdown`). Declared explicitly so consumers know how to slice the string — e.g. JavaScript strings are UTF-16, so a naive `.slice()` drifts when the markdown contains astral characters.',
        title='Range Units',
    )


class V2ExtractOptions(BaseModel):
    """
    Extraction options (``docs/extract-v2-proposal.md`` → Options).
    """

    strict: Optional[bool] = Field(
        False,
        description='When ``true``, returns HTTP 422 if the schema contains fields the model cannot extract. When ``false`` (default), unsupported fields are skipped and extraction continues.',
        title='Strict',
    )


class V2WorkflowMetadata(BaseModel):
    """
    Response metadata for a v2 workflow call
    (``docs/pipeline-v2-proposal.md`` → Top-level metadata).
    """

    billing: Optional[V2Billing] = Field(
        None,
        description='Billing summary: the service tier the request ran in and the credits charged.',
    )
    credit_usage: Optional[float] = Field(
        0.0,
        description='Combined credits billed for this request (parse + extract).',
        title='Credit Usage',
    )
    duration_ms: int = Field(
        ...,
        description='Total end-to-end duration across all stages in milliseconds.',
        title='Duration Ms',
    )
    job_id: str = Field(
        ..., description='Gateway job id (workflow id).', title='Job Id'
    )
    openapi_spec: str = Field(
        ...,
        description='URL of the OpenAPI spec covering this API, for inspection and client generation.',
    )


class ValidationError(BaseModel):
    ctx: Optional[dict[str, Any]] = Field(None, title='Context')
    input: Optional[Any] = Field(None, title='Input')
    loc: list[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class WorkflowDocumentInput(BaseModel):
    """
    One declared document input in the ``inputs`` map.

    A caller supplies exactly one of ``document`` or ``document_url``:

    * ``document`` — name of a multipart form part carrying the raw bytes. The
      gateway stages those bytes internally before the workflow runs.
    * ``document_url`` — public URL (SSRF-validated at submit; fetched and staged
      by the gateway before the workflow starts).
    """

    document: Optional[str] = Field(
        None,
        description='Name of the multipart form part carrying the document bytes. The gateway resolves this to an internal ref before validation; it is not stored in the final request object.',
        examples=['report_pdf'],
        title='Document',
    )
    document_url: Optional[str] = Field(
        None,
        description='URL to fetch the document from. Must be a public http(s) URL; private/loopback IPs are rejected at submit time.',
        title='Document Url',
    )


class Page1(RootModel[int]):
    root: int = Field(..., ge=1)


class WorkflowStepOptions(BaseModel):
    """
    Unified options for the ``parse-extract`` prebuilt step.

    ``pages`` applies to the parse stage; ``strict`` applies to the extract
    stage. Omit entirely to use each stage's defaults.
    """

    pages: Optional[list[Page1]] = Field(
        None,
        description='1-indexed page numbers to process. ``null`` = all pages. Values < 1 are rejected; numbers > page_count are silently ignored.',
        title='Pages',
    )
    strict: Optional[bool] = Field(
        False,
        description='When ``true``, returns 422 if the schema contains fields the model cannot extract. When ``false``, unsupported fields are skipped.',
        title='Strict',
    )


class BlocksOptions(BaseModel):
    attestation: Optional[BaseElementOptions] = None
    card: Optional[BaseElementOptions] = None
    figure: Optional[FigureOptions] = None
    logo: Optional[BaseElementOptions] = None
    marginalia: Optional[BaseElementOptions] = None
    scan_code: Optional[BaseElementOptions] = None
    table: Optional[TableOptions] = None
    text: Optional[BaseElementOptions] = None


class Grounding(BaseModel):
    """
    Where a node lives: its page, its slice of `markdown`, and its box.

    The same shape is used for page nodes, element nodes, and each
    `atomic_grounding` entry, so any grounding object is self-contained — it
    can be lifted out of the tree and still locates its content.
    """

    box: Box = Field(
        ...,
        description="Bounding box in normalized page coordinates (`0`–`1` fractions of page width/height, at most 8 decimal places). A page node's box is always the full page `{0, 0, 1, 1}`.",
    )
    page: int = Field(
        ...,
        description="1-indexed page number this grounding is on. On a page node, the page's own number.",
        title='Page',
    )
    range: Range = Field(
        ...,
        description='`[start, end)` offsets into the top-level `markdown` string covered by this node or segment.',
    )


class HTTPValidationError(BaseModel):
    detail: Optional[list[ValidationError]] = Field(None, title='Detail')


class PrebuiltWorkflowStep(BaseModel):
    """
    A Phase 1 step: references a server-defined pipeline by name.

    The ``name`` identifies the prebuilt pipeline to run AND becomes the key
    under which this step's result appears in the response ``output`` map.
    The ``document`` field is a reference into the ``inputs`` namespace
    (``"$inputs.<logical-name>"``).
    """

    document: str = Field(
        ...,
        description='Reference into the ``inputs`` namespace, e.g. ``"$inputs.report"``. The referenced input must be declared in the ``inputs`` form field.',
        title='Document',
    )
    name: Literal['parse-extract'] = Field(
        ...,
        description='Workflow to run — doubles as the result key in ``output``. v1 only: ``"parse-extract"``.',
        title='Name',
    )
    options: Optional[WorkflowStepOptions] = Field(
        None, description='Parse + extract options for this step. Omit for defaults.'
    )
    schema_: dict[str, Any] = Field(
        ...,
        alias='schema',
        description='JSON Schema for fields to extract.',
        examples=[{'properties': {'revenue': {'type': 'string'}}, 'type': 'object'}],
        title='Schema',
    )


class Element(BaseModel):
    """
    Hierarchical document element. All non-page elements share this shape.

    Keys off `type`; optional fields are excluded from the serialized JSON
    via ``exclude_none=True`` when not set.
    """

    atomic_grounding: Optional[list[Grounding]] = Field(
        None,
        description="Fine-grained grounding segments at the model's current granularity (visual lines today; finer in future versions, same schema). Present only on leaf elements — every type except `table`. `[]` only when segments are structurally impossible: `table_cell` (a cell has no finer granularity than itself) and elements whose markdown is suppressed via `blocks.<type>.markdown=false`. Any other leaf the model could not segment finer carries a single entry covering the element's full range and box. Omitted entirely when `options.atomic_grounding` is `false`.",
        title='Atomic Grounding',
    )
    children: Optional[list[Element]] = Field(
        None,
        description='The cells (`table_cell` elements) of a `table` element. Present only when `type` is `table`.',
        title='Children',
    )
    col: Optional[int] = Field(
        None,
        description='0-indexed column position of this cell within its parent `table`. Present only on `table_cell` elements.',
        title='Col',
    )
    colspan: Optional[int] = Field(
        None,
        description='Number of columns this cell spans. `1` for unmerged cells. Present only on `table_cell` elements.',
        title='Colspan',
    )
    grounding: Grounding = Field(
        ...,
        description="The element's spatial data: the page it appears on, its `[start, end)` range in the top-level `markdown` string, and its bounding box in normalized page coordinates.",
    )
    id: str = Field(
        ...,
        description='Semantic element id, unique within the document. Format `<type>-<index>`, where `<index>` is a per-type 0-based counter assigned in reading order — `text-0` is the first text element in the document, `figure-0` the first figure, `table_cell-0` the first cell of the first table. Stable within a response but not across re-parses of the same document.',
        title='Id',
    )
    markdown: Optional[str] = Field(
        None,
        description='The element\'s slice of the top-level `markdown` string (`markdown[grounding.range.start:grounding.range.end]`). `""` for zero-length ranges (e.g. blocks suppressed via `blocks.<type>.markdown=false`). Present only when `options.inline_markdown` is `true`.',
        title='Markdown',
    )
    row: Optional[int] = Field(
        None,
        description='0-indexed row position of this cell within its parent `table`. Present only on `table_cell` elements.',
        title='Row',
    )
    rowspan: Optional[int] = Field(
        None,
        description='Number of rows this cell spans. `1` for unmerged cells. Present only on `table_cell` elements.',
        title='Rowspan',
    )
    type: Type = Field(
        ...,
        description='The element type. Determines which optional fields appear on this element.',
        title='Type',
    )


class Page(BaseModel):
    children: Optional[list[Element]] = Field(
        None,
        description='The elements detected on this page, in reading order. Empty for failed pages.',
        title='Children',
    )
    grounding: Grounding = Field(
        ...,
        description="The page's spatial data: `page` is the 1-indexed page number in the source document (not contiguous when `options.pages` filters out some pages); `range` covers this page's content in the top-level `markdown` string (zero-length `start == end` for failed pages); `box` is always the full page `{0, 0, 1, 1}`.",
    )
    markdown: Optional[str] = Field(
        None,
        description='This page\'s slice of the top-level `markdown` string (`markdown[grounding.range.start:grounding.range.end]`). `""` for failed pages. Present only when `options.inline_markdown` is `true`.',
        title='Markdown',
    )
    reason: Optional[str] = Field(
        None,
        description='Failure reason. Present only when `status` is `failed`.',
        title='Reason',
    )
    status: Optional[Status] = Field(
        'ok',
        description='Whether this page was parsed successfully (`ok`) or failed (`failed`).',
        title='Status',
    )
    type: Literal['page'] = Field(
        'page',
        description='The node type. Identifies this node as a page in the structure tree.',
        title='Type',
    )


class Document(BaseModel):
    children: Optional[list[Page]] = Field(
        None,
        description='The pages of the document, in source order.',
        title='Children',
    )
    markdown: Optional[str] = Field(
        None,
        description='The full document markdown — identical to the top-level `markdown` field, included so the structure tree is self-contained. Present only when `options.inline_markdown` is `true`.',
        title='Markdown',
    )
    type: Literal['document'] = Field(
        'document',
        description='The node type. Identifies this node as the root of the structure tree.',
        title='Type',
    )


class ParseResponse(BaseModel):
    """
    The parse result: the full document as `markdown`, its hierarchical
    `structure` (with per-node spatial `grounding` inline), and request
    `metadata`.
    """

    markdown: str = Field(
        ...,
        description='The full document as a single Markdown string, in reading order.',
        title='Markdown',
    )
    metadata: ParseMetadata = Field(
        ...,
        description='Information about the request: model version, page count, duration, billing, and more.',
    )
    structure: Document = Field(
        ...,
        description="The document's hierarchical structure: pages and the elements detected on each page. Every node below the root carries its spatial data inline in a `grounding` object (`{page, range, box}`, normalized page coordinates); leaf elements additionally carry `atomic_grounding`.",
    )


Element.model_rebuild()
